
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;
	private global::Gtk.Table table1;
	private global::Gtk.Button buttonCalculadora;
	private global::Gtk.Button buttonEditor;
	private global::Gtk.Button buttonNavegador;
	private global::Gtk.Button buttonTerminal;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.table1 = new global::Gtk.Table (((uint)(3)), ((uint)(3)), false);
		this.table1.Name = "table1";
		this.table1.RowSpacing = ((uint)(6));
		this.table1.ColumnSpacing = ((uint)(6));
		// Container child table1.Gtk.Table+TableChild
		this.buttonCalculadora = new global::Gtk.Button ();
		this.buttonCalculadora.CanFocus = true;
		this.buttonCalculadora.Name = "buttonCalculadora";
		this.buttonCalculadora.UseUnderline = true;
		this.buttonCalculadora.Label = global::Mono.Unix.Catalog.GetString ("Calculadora");
		this.table1.Add (this.buttonCalculadora);
		global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table1 [this.buttonCalculadora]));
		w1.TopAttach = ((uint)(2));
		w1.BottomAttach = ((uint)(3));
		w1.LeftAttach = ((uint)(2));
		w1.RightAttach = ((uint)(3));
		w1.XOptions = ((global::Gtk.AttachOptions)(4));
		w1.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.buttonEditor = new global::Gtk.Button ();
		this.buttonEditor.CanFocus = true;
		this.buttonEditor.Name = "buttonEditor";
		this.buttonEditor.UseUnderline = true;
		this.buttonEditor.Label = global::Mono.Unix.Catalog.GetString ("Editor");
		this.table1.Add (this.buttonEditor);
		global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1 [this.buttonEditor]));
		w2.LeftAttach = ((uint)(2));
		w2.RightAttach = ((uint)(3));
		w2.XOptions = ((global::Gtk.AttachOptions)(4));
		w2.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.buttonNavegador = new global::Gtk.Button ();
		this.buttonNavegador.CanFocus = true;
		this.buttonNavegador.Name = "buttonNavegador";
		this.buttonNavegador.UseUnderline = true;
		this.buttonNavegador.Label = global::Mono.Unix.Catalog.GetString ("Navegador");
		this.table1.Add (this.buttonNavegador);
		global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1 [this.buttonNavegador]));
		w3.TopAttach = ((uint)(2));
		w3.BottomAttach = ((uint)(3));
		w3.XOptions = ((global::Gtk.AttachOptions)(4));
		w3.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.buttonTerminal = new global::Gtk.Button ();
		this.buttonTerminal.CanFocus = true;
		this.buttonTerminal.Name = "buttonTerminal";
		this.buttonTerminal.UseUnderline = true;
		this.buttonTerminal.Label = global::Mono.Unix.Catalog.GetString ("Terminal");
		this.table1.Add (this.buttonTerminal);
		global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1 [this.buttonTerminal]));
		w4.XOptions = ((global::Gtk.AttachOptions)(4));
		w4.YOptions = ((global::Gtk.AttachOptions)(4));
		this.vbox1.Add (this.table1);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.table1]));
		w5.Position = 1;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
